name: Deployment1
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        run: actions/checkout@3
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Bulild code
        run: npm run build
      - name: Deploy Code
        run: echo "Deploying..."
